In [1]:
import pandas as pd
import os
from urllib.parse import urljoin

In [2]:
raiz = os.path.abspath(os.getcwd())
url = urljoin(f'{raiz}/', 'data')
url

'/home/dmateons/Documents/mateo/python/xlsx_csv_to_sql/data'

In [3]:
df = pd.read_csv(f'{url}/BEGIN_SET_NOCOUNT_ON_DECLARE_USER_INFO_TEMP_TABLE_TABLE_id_INT__202206281035.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22182 entries, 0 to 22181
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         22153 non-null  object
 1   login        22182 non-null  object
 2   roles        22182 non-null  object
 3   permissions  10411 non-null  object
 4   enabled      22182 non-null  int64
dtypes: int64(1), object(4)
memory usage: 866.6+ KB

In [4]:
df.head()

,name,login,roles,permissions,enabled
0,Alonso Portuguez Supervisor,aportuguez@a365.com.pe,"SUPERVISOR,REPORTERIA",NaN,1
1,Daniel Predes,daniel.paredes@coopeuch.cl - 11506,AGENTE,"Grupos,Outbound",0
2,Daian Molina,fransesca.jnb20@gmail.com - 13696,AGENTE,NaN,0
3,Ingrid Viviana Puentes Ortega,ipuentes@javesalud.com.co - 12986,SUPERVISOR,"Reportería,Programar reportes",0
4,Jorge Pérez,jorge.perez@coopeuch.cl - 10911,AGENTE,"Configuración,Programar reportes,Consumo,Repor...",0

In [5]:
df_1 = df[df.enabled == 1]
df_1

,name,login,roles,permissions,enabled
0,Alonso Portuguez Supervisor,aportuguez@a365.com.pe,"SUPERVISOR,REPORTERIA",NaN,1
7,Marinaro Rosa,rmarinaro@redsos.com.ar,AGENTE,NaN,1
18,Luis Cedeño,l.Cedeno_agente@concentra.com.do,AGENTE,NaN,1
19,Luis Cedeño,l.Cedeno_super@concentra.com.do,SUPERVISOR,NaN,1
20,Chattigo Prueba,1,AGENTE,NaN,1
...,...,...,...,...,...
22169,Rodriguez Usuga Zoraida,zoraida.usuga@sura.com.co,AGENTE,"Outbound,Grupos",1
22170,ZORAIDA PALACIOS RENGIFO,ZoraidaPalacios.Contratista@comfama.com,AGENTE,"Outbound,Agente Legacy",1
22179,Zusel Vega Condor,zvega@a365.com.pe,"SUPERVISOR,REPORTERIA","Reportería,Programar reportes",1
22180,Zulman Yulieth Zapata Garcia,zzapata@sura.com.co,AGENTE,Outbound,1
22181,Zurelly Zapata,zzapataa@sura.com.co,AGENTE,"Outbound,Agendamiento,Agente Legacy",1

In [6]:
df_2 = df_1[~df_1.roles.isin(['SUPERVISOR', 'AGENTE', 'AGENTE,SUPERVISOR'])]
df_2

,name,login,roles,permissions,enabled
0,Alonso Portuguez Supervisor,aportuguez@a365.com.pe,"SUPERVISOR,REPORTERIA",NaN,1
193,Supervisor Pruebas,2,"SUPERVISOR,REPORTERIA","Reportería,Programar reportes",1
196,21 siglo chattigo,21siglo@chattigo,"SUPERVISOR,SOPORTE_MONITOREO,REPORTERIA","Configuración,Reportería,Programar reportes",1
244,IVAN MAURICIO JIMENEZ CAÑON,80882020@sura.com,"ADMINISTRADOR,AGENTE",NaN,1
274,admin konecta,a@a.com,ADMINISTRADOR,NaN,1
...,...,...,...,...,...
22042,PALACIOS ROZO YENIFER ROSANA - SURA,yrpalacios@sura.com.co,"SUPERVISOR,REPORTERIA,AGENTE","Reportería,Programar reportes",1
22045,Yanina Sorondo,ysorondo@redsos.com.ar,"SUPERVISOR,REPORTERIA","Reportería,Programar reportes,Configuración",1
22054,YUDY ELENA ARROYAVE MADRIGAL,yudy.arroyave.m@sura.com.co,"SUPERVISOR,REPORTERIA","Reportería,Programar reportes,Configuración",1
22141,Yeraldin Zapata Castrillon,yzapatac@sura.com.co,"AGENTE,SUPERVISOR,REPORTERIA","Reportería,Programar reportes,Configuración",1
22179,Zusel Vega Condor,zvega@a365.com.pe,"SUPERVISOR,REPORTERIA","Reportería,Programar reportes",1